"""add is_archived

Revision ID: 107b92ca0d9a
Revises: f4390a2e845f
Create Date: 2026-07-22 11:55:27.361783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '107b92ca0d9a'
down_revision = 'f4390a2e845f'
branch_labels = None
depends_on = None


def upgrade():

    op.execute("CREATE TYPE statusenum AS ENUM ('NOTAPPLIED', 'APPLIED', 'INTERVIEWING', 'ACCEPTED', 'ARCHIVED')")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_status', sa.Enum('NOTAPPLIED', 'APPLIED', 'INTERVIEWING', 'ACCEPTED', 'ARCHIVED', name='statusenum'), server_default='NOTAPPLIED', nullable=False))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('user_jobs_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_jobs_job_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('applied')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('user_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_jobs_job_id_fkey'), 'jobs', ['job_id'], ['id'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('user_jobs_user_id_fkey'), 'users', ['user_id'], ['id'], deferrable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('is_archived')
        batch_op.drop_column('application_status')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.execute("DROP TYPE statusenum")
    # ### end Alembic commands ###
